# Generated by Django 4.0.6 on 2022-07-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=1200, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('noofviews', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='writeenby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=10)),
            ],
        ),
    ]
