# Generated by Django 4.0.6 on 2022-07-13 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogwebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blodid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogid', to='blogwebsite.writeenby'),
            preserve_default=False,
        ),
    ]
