# Generated by Django 4.0.6 on 2022-07-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogwebsite', '0002_blogs_blodid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='writeenby',
        ),
    ]
