# Generated by Django 4.0.6 on 2022-07-13 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogwebsite', '0003_delete_blogs_delete_writeenby'),
    ]

    operations = [
        migrations.CreateModel(
            name='writeenby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=10)),
                ('authorid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=1200, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('blodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogid', to='blogwebsite.writeenby')),
            ],
        ),
    ]
