# Generated by Django 4.0.6 on 2022-07-14 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogwebsite', '0006_alter_blogs_blodid_delete_writeenby'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentonblog', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('blogname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogwebsite.blogs')),
                ('commentatorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
