# Generated by Django 4.0.5 on 2022-07-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogwebsite', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='no_of_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
